# Generated by Django 3.2.4 on 2022-06-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0002_auto_20220617_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='des_product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DigitalPrintingPress.product'),
            preserve_default=False,
        ),
    ]
