# Generated by Django 4.0.4 on 2022-06-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0003_productdescription_des_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='detail_title',
        ),
    ]
