# Generated by Django 4.0.4 on 2022-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0005_productdetail_detail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='detail_Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='detail_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
