# Generated by Django 3.2.4 on 2022-06-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0007_auto_20220620_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='description_detail',
            new_name='description_TitleWithdetail',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='descripton_title',
        ),
    ]
