# Generated by Django 4.0.4 on 2022-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0009_alter_cart_cart_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_photo',
            field=models.ImageField(null=True, upload_to='uploads/cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='textprint',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
