# Generated by Django 4.0.4 on 2022-07-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0010_alter_cart_cart_photo_alter_cart_textprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('adress_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shipping_address', models.TextField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'adress',
            },
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='pk_customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address',
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_id'], name='pk_user'),
        ),
        migrations.AddField(
            model_name='adress',
            name='Adress_customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalPrintingPress.customer'),
        ),
        migrations.AddIndex(
            model_name='adress',
            index=models.Index(fields=['Adress_customer_id'], name='pk_customer'),
        ),
    ]
