# Generated by Django 3.2.4 on 2022-09-02 05:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DigitalPrintingPress', '0011_adress_remove_customer_pk_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_detail_description_TitleWithdetail', models.TextField(default='', max_length=3000)),
                ('order_detail_qty', models.IntegerField()),
                ('order_detail_totalamount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('order_detail_textprint', models.CharField(max_length=100, null=True)),
                ('order_detail_photo', models.ImageField(null=True, upload_to='uploads/orderDetail')),
                ('order_detail_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_detail_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalPrintingPress.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], max_length=20)),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('orderDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalPrintingPress.orderdetail')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
