# Generated by Django 3.2.4 on 2022-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0012_auto_20220902_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transcation_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
