# Generated by Django 3.2.4 on 2022-09-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0014_order_adressid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transcation_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='transcation_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
