# Generated by Django 4.0.4 on 2022-09-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0015_auto_20220902_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDetail',
        ),
        migrations.AddField(
            model_name='order',
            name='Order_transcation_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
