# Generated by Django 4.0.4 on 2022-09-03 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DigitalPrintingPress', '0016_remove_order_orderdetail_order_order_transcation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='Adress_customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
