# Generated by Django 4.0.4 on 2022-09-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0017_alter_adress_adress_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_totalamount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
