# Generated by Django 4.0.4 on 2022-09-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalPrintingPress', '0018_order_order_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adressid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sub_category_id',
            field=models.ForeignKey(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], on_delete=django.db.models.deletion.CASCADE, to='DigitalPrintingPress.subcategory'),
        ),
    ]
